POST http://localhost:5202/api/v1/tickets
Content-Type: application/json

{
  "jiraEmail": "bot@company.com",
  "jiraApiToken": "ATATT3xFfGF0...",
  "jiraSiteUrl": "https://yoursite.atlassian.net",
  "tickets": [
    {
      "title": "Stale API key: prod-gateway",
      "description": "Last rotated 365 days ago.",
      "projectKey": "KAN",
      "priority": "High"
    },
    {
      "title": "Stale API key: prod-gateway",
      "description": "Last rotated 365 days ago.",
      "projectKey": "KAN",
      "priority": "High"
    },
    {
      "title": "Stale API key: prod-gateway",
      "description": "Last rotated 365 days ago.",
      "projectKey": "KAN",
      "priority": "High"
    },
    {
      "title": "Stale API key: prod-gateway",
      "description": "Last rotated 365 days ago.",
      "projectKey": "KAN",
      "priority": "High"
    },
    {
      "title": "Stale API key: prod-gateway",
      "description": "Last rotated 365 days ago.",
      "projectKey": "KAN",
      "priority": "High"
    },
    {
      "title": "Stale API key: prod-gateway",
      "description": "Last rotated 365 days ago.",
      "projectKey": "KAN",
      "priority": "High"
    },
    {
      "title": "Stale API key: prod-gateway",
      "description": "Last rotated 365 days ago.",
      "projectKey": "KAN",
      "priority": "High"
    },
    {
      "title": "Stale API key: prod-gateway",
      "description": "Last rotated 365 days ago.",
      "projectKey": "KAN",
      "priority": "High"
    },
    {
      "title": "Stale API key: prod-gateway",
      "description": "Last rotated 365 days ago.",
      "projectKey": "KAN",
      "priority": "High"
    },
    {
      "title": "Stale API key: prod-gateway",
      "description": "Last rotated 365 days ago.",
      "projectKey": "KAN",
      "priority": "High"
    },
    {
      "title": "Stale API key: prod-gateway",
      "description": "Last rotated 365 days ago.",
      "projectKey": "KAN",
      "priority": "High"
    },
    {
      "title": "Stale API key: prod-gateway",
      "description": "Last rotated 365 days ago.",
      "projectKey": "KAN",
      "priority": "High"
    },
    {
      "title": "Stale API key: prod-gateway",
      "description": "Last rotated 365 days ago.",
      "projectKey": "KAN",
      "priority": "High"
    }
  ]
}

###